name: one_on_one_mahjong
description: Mahjong game we can fight one-on-one

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  flame: ^1.2.0
  localstorage: ^4.0.0+1
  enum_to_string: ^2.0.1
  collection: ^1.15.0
  flutter_riverpod: ^1.0.4
  google_mobile_ads: ^1.2.0
  audioplayers: ^0.20.1
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.0
  email_validator: ^2.0.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - .env

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon/appIcon.png"
